[2015-12-22 01:19:32,048][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: initializing ...
[2015-12-22 01:19:32,054][INFO ][plugins                  ] [Jack-in-the-Box] loaded [], sites []
[2015-12-22 01:19:34,147][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: initialized
[2015-12-22 01:19:34,148][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: starting ...
[2015-12-22 01:19:34,271][INFO ][transport                ] [Jack-in-the-Box] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.1.4:9300]}
[2015-12-22 01:19:37,330][INFO ][cluster.service          ] [Jack-in-the-Box] new_master [Jack-in-the-Box][hZ9qJO-YTEq2R9tVFtinEA][inet[/192.168.1.4:9300]], reason: zen-disco-join (elected_as_master)
[2015-12-22 01:19:37,425][INFO ][discovery                ] [Jack-in-the-Box] elasticsearch/hZ9qJO-YTEq2R9tVFtinEA
[2015-12-22 01:19:37,440][INFO ][http                     ] [Jack-in-the-Box] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.1.4:9200]}
[2015-12-22 01:19:37,440][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: started
[2015-12-22 01:19:38,049][INFO ][gateway                  ] [Jack-in-the-Box] recovered [1] indices into cluster_state
[2015-12-22 01:19:39,859][INFO ][node                     ] [Venom] {0.20.6}[39408]: initializing ...
[2015-12-22 01:19:39,865][INFO ][plugins                  ] [Venom] loaded [], sites []
[2015-12-22 01:19:41,722][INFO ][node                     ] [Venom] {0.20.6}[39408]: initialized
[2015-12-22 01:19:41,723][INFO ][node                     ] [Venom] {0.20.6}[39408]: starting ...
[2015-12-22 01:19:41,794][INFO ][transport                ] [Venom] bound_address {inet[/0:0:0:0:0:0:0:0:9301]}, publish_address {inet[/192.168.1.4:9301]}
[2015-12-22 01:19:44,900][INFO ][cluster.service          ] [Jack-in-the-Box] added {[Venom][yasaeBY6Q6Ovg-QqtjieIw][inet[/192.168.1.4:9301]],}, reason: zen-disco-receive(join from node[[Venom][yasaeBY6Q6Ovg-QqtjieIw][inet[/192.168.1.4:9301]]])
[2015-12-22 01:19:44,911][INFO ][cluster.service          ] [Venom] detected_master [Jack-in-the-Box][hZ9qJO-YTEq2R9tVFtinEA][inet[/192.168.1.4:9300]], added {[Jack-in-the-Box][hZ9qJO-YTEq2R9tVFtinEA][inet[/192.168.1.4:9300]],}, reason: zen-disco-receive(from master [[Jack-in-the-Box][hZ9qJO-YTEq2R9tVFtinEA][inet[/192.168.1.4:9300]]])
[2015-12-22 01:19:44,934][INFO ][discovery                ] [Venom] elasticsearch/yasaeBY6Q6Ovg-QqtjieIw
[2015-12-22 01:19:44,939][INFO ][http                     ] [Venom] bound_address {inet[/0:0:0:0:0:0:0:0:9201]}, publish_address {inet[/192.168.1.4:9201]}
[2015-12-22 01:19:44,940][INFO ][node                     ] [Venom] {0.20.6}[39408]: started
[2015-12-22 01:19:51,895][INFO ][node                     ] [Venom] {0.20.6}[39408]: stopping ...
[2015-12-22 01:19:51,949][INFO ][cluster.service          ] [Jack-in-the-Box] removed {[Venom][yasaeBY6Q6Ovg-QqtjieIw][inet[/192.168.1.4:9301]],}, reason: zen-disco-node_left([Venom][yasaeBY6Q6Ovg-QqtjieIw][inet[/192.168.1.4:9301]])
[2015-12-22 01:19:51,965][INFO ][node                     ] [Venom] {0.20.6}[39408]: stopped
[2015-12-22 01:19:51,965][INFO ][node                     ] [Venom] {0.20.6}[39408]: closing ...
[2015-12-22 01:19:51,970][INFO ][node                     ] [Venom] {0.20.6}[39408]: closed
[2015-12-22 09:41:05,453][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: stopping ...
[2015-12-22 09:41:05,495][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: stopped
[2015-12-22 09:41:05,495][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: closing ...
[2015-12-22 09:41:05,502][INFO ][node                     ] [Jack-in-the-Box] {0.20.6}[39395]: closed
[2015-12-22 09:41:30,274][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: initializing ...
[2015-12-22 09:41:30,278][INFO ][plugins                  ] [Evilhawk‎] loaded [], sites []
[2015-12-22 09:41:32,696][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: initialized
[2015-12-22 09:41:32,697][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: starting ...
[2015-12-22 09:41:32,845][INFO ][transport                ] [Evilhawk‎] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.20.15:9300]}
[2015-12-22 09:41:35,892][INFO ][cluster.service          ] [Evilhawk‎] new_master [Evilhawk‎][--k9kTGMTNqFzIDDFYA78A][inet[/192.168.20.15:9300]], reason: zen-disco-join (elected_as_master)
[2015-12-22 09:41:35,974][INFO ][discovery                ] [Evilhawk‎] elasticsearch/--k9kTGMTNqFzIDDFYA78A
[2015-12-22 09:41:35,989][INFO ][http                     ] [Evilhawk‎] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.20.15:9200]}
[2015-12-22 09:41:35,990][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: started
[2015-12-22 09:41:36,410][INFO ][gateway                  ] [Evilhawk‎] recovered [1] indices into cluster_state
[2015-12-22 09:42:12,622][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: stopping ...
[2015-12-22 09:42:12,667][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: stopped
[2015-12-22 09:42:12,668][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: closing ...
[2015-12-22 09:42:12,673][INFO ][node                     ] [Evilhawk‎] {0.20.6}[42340]: closed
[2015-12-22 09:42:30,708][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: initializing ...
[2015-12-22 09:42:30,723][INFO ][plugins                  ] [Prime Mover] loaded [], sites []
[2015-12-22 09:42:32,556][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: initialized
[2015-12-22 09:42:32,557][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: starting ...
[2015-12-22 09:42:32,655][INFO ][transport                ] [Prime Mover] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.20.15:9300]}
[2015-12-22 09:42:35,698][INFO ][cluster.service          ] [Prime Mover] new_master [Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]], reason: zen-disco-join (elected_as_master)
[2015-12-22 09:42:35,773][INFO ][discovery                ] [Prime Mover] elasticsearch/iZVy0ay4QfW06RX0QWqmTw
[2015-12-22 09:42:35,786][INFO ][http                     ] [Prime Mover] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.20.15:9200]}
[2015-12-22 09:42:35,786][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: started
[2015-12-22 09:42:36,240][INFO ][gateway                  ] [Prime Mover] recovered [1] indices into cluster_state
[2015-12-22 12:18:43,934][DEBUG][action.index             ] [Prime Mover] [listings][2], node[iZVy0ay4QfW06RX0QWqmTw], [P], s[STARTED]: Failed to execute [index {[listings][listing][20], source[{"name":"Cyberia Smart House","body":"Cyberia follows the lives and translates the experiences of the first few people who realized that our culture was about to take a leap into the unknown. Some of them have succeeded beyond their wildest expectations and are now practically household names. Others have met with catastrophe. Still others have simply faded from view, their own contributions to the cyberian renaissance already completed.\r\n\r\nThe people in this book, and thousands of others like them around the world, understand the implications of our technologies on our culture, thought systems, spiritual beliefs, and even our biological evolution. They still stand as the most optimistic and forward-thinking appraisers of our civilization’s fate. As we draw ever nearer to the consensually hallucinatory reality for which these cyberians drew the blueprints, their impressions of life on the edge become even more relevant for the rest of us. And they make more sense.","start":"12/17/15","end":"12/23/15","price":2131,"num_of_guest":5,"room_type":"Entire home","picture":[{"url":"/uploads/tmp/1450757919-40637-4874/2.jpg","thumb":{"url":"/uploads/tmp/1450757919-40637-4874/thumb_2.jpg"},"main":{"url":"/uploads/tmp/1450757919-40637-4874/main_2.jpg"}},{"url":"/uploads/tmp/1450757919-40637-3652/Cyberia_SmartHomes__12__small.JPG","thumb":{"url":"/uploads/tmp/1450757919-40637-3652/thumb_Cyberia_SmartHomes__12__small.JPG"},"main":{"url":"/uploads/tmp/1450757919-40637-3652/main_Cyberia_SmartHomes__12__small.JPG"}}],"address_formatted_address":"","address_street_number":"","address_street_name":"","address_street":"","address_city":"","address_zip_code":"","address_department":"","address_department_code":"","address_state":"","address_state_code":"","address_country":"","address_country_code":"","address_lat":null,"address_lng":null,"user_id":3,"created_at":"2015-12-22T04:18:43.786Z","updated_at":"2015-12-22T04:18:43.786Z"}]}]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [start]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:320)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:587)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:486)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:430)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:318)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [12/17/15], tried both date format [dateOptionalTime], and timestamp number
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:432)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:361)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:182)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:307)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "12/17/15" is malformed at "/17/15"
	at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:747)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:426)
	... 14 more
[2015-12-22 12:18:51,508][DEBUG][action.index             ] [Prime Mover] [listings][3], node[iZVy0ay4QfW06RX0QWqmTw], [P], s[STARTED]: Failed to execute [index {[listings][listing][21], source[{"name":"Cyberia Smart House","body":"Cyberia follows the lives and translates the experiences of the first few people who realized that our culture was about to take a leap into the unknown. Some of them have succeeded beyond their wildest expectations and are now practically household names. Others have met with catastrophe. Still others have simply faded from view, their own contributions to the cyberian renaissance already completed.\r\n\r\nThe people in this book, and thousands of others like them around the world, understand the implications of our technologies on our culture, thought systems, spiritual beliefs, and even our biological evolution. They still stand as the most optimistic and forward-thinking appraisers of our civilization’s fate. As we draw ever nearer to the consensually hallucinatory reality for which these cyberians drew the blueprints, their impressions of life on the edge become even more relevant for the rest of us. And they make more sense.","start":"12/17/15","end":"12/23/15","price":2131,"num_of_guest":5,"room_type":"Entire home","picture":[{"url":"/uploads/tmp/1450757930-40637-0358/2.jpg","thumb":{"url":"/uploads/tmp/1450757930-40637-0358/thumb_2.jpg"},"main":{"url":"/uploads/tmp/1450757930-40637-0358/main_2.jpg"}},{"url":"/uploads/tmp/1450757930-40637-8362/Cyberia_SmartHomes__12__small.JPG","thumb":{"url":"/uploads/tmp/1450757930-40637-8362/thumb_Cyberia_SmartHomes__12__small.JPG"},"main":{"url":"/uploads/tmp/1450757930-40637-8362/main_Cyberia_SmartHomes__12__small.JPG"}}],"address_formatted_address":"Cyber 8, 63000 Cyberjaya, Selangor, Malaysia","address_street_number":"","address_street_name":"","address_street":"","address_city":"Cyberjaya","address_zip_code":"63000","address_department":"","address_department_code":"","address_state":"Selangor","address_state_code":"Selangor","address_country":"Malaysia","address_country_code":"MY","address_lat":2.910878,"address_lng":101.6561711,"user_id":3,"created_at":"2015-12-22T04:18:51.430Z","updated_at":"2015-12-22T04:18:51.430Z"}]}]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [start]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:320)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:587)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:486)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:430)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:318)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [12/17/15], tried both date format [dateOptionalTime], and timestamp number
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:432)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:361)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:182)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:307)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "12/17/15" is malformed at "/17/15"
	at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:747)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:426)
	... 14 more
[2015-12-22 12:23:14,625][DEBUG][action.index             ] [Prime Mover] [listings][4], node[iZVy0ay4QfW06RX0QWqmTw], [P], s[STARTED]: Failed to execute [index {[listings][listing][22], source[{"name":"Cyberia","body":"adsda","start":"12/03/15","end":"12/23/15","price":null,"num_of_guest":7,"room_type":"Entire home","picture":[{"url":"/uploads/tmp/1450758190-40637-6877/2.jpg","thumb":{"url":"/uploads/tmp/1450758190-40637-6877/thumb_2.jpg"},"main":{"url":"/uploads/tmp/1450758190-40637-6877/main_2.jpg"}},{"url":"/uploads/tmp/1450758190-40637-0617/Cyberia_SmartHomes__12__small.JPG","thumb":{"url":"/uploads/tmp/1450758190-40637-0617/thumb_Cyberia_SmartHomes__12__small.JPG"},"main":{"url":"/uploads/tmp/1450758190-40637-0617/main_Cyberia_SmartHomes__12__small.JPG"}}],"address_formatted_address":null,"address_street_number":null,"address_street_name":null,"address_street":null,"address_city":null,"address_zip_code":null,"address_department":null,"address_department_code":null,"address_state":null,"address_state_code":null,"address_country":null,"address_country_code":null,"address_lat":null,"address_lng":null,"user_id":3,"created_at":"2015-12-22T04:23:14.421Z","updated_at":"2015-12-22T04:23:14.421Z"}]}]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [start]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:320)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:587)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:486)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:430)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:318)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [12/03/15], tried both date format [dateOptionalTime], and timestamp number
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:432)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:361)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:182)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:307)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "12/03/15" is malformed at "/03/15"
	at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:747)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:426)
	... 14 more
[2015-12-22 17:17:17,442][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: initializing ...
[2015-12-22 17:17:17,447][INFO ][plugins                  ] [Enforcer] loaded [], sites []
[2015-12-22 17:17:19,165][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: initialized
[2015-12-22 17:17:19,165][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: starting ...
[2015-12-22 17:17:19,245][INFO ][transport                ] [Enforcer] bound_address {inet[/0:0:0:0:0:0:0:0:9301]}, publish_address {inet[/192.168.20.15:9301]}
[2015-12-22 17:17:22,322][INFO ][cluster.service          ] [Prime Mover] added {[Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]],}, reason: zen-disco-receive(join from node[[Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]])
[2015-12-22 17:17:22,340][INFO ][cluster.service          ] [Enforcer] detected_master [Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]], added {[Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]],}, reason: zen-disco-receive(from master [[Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]]])
[2015-12-22 17:17:22,359][INFO ][discovery                ] [Enforcer] elasticsearch/u1kdcT1TTi2lwRKsI-haAg
[2015-12-22 17:17:22,366][INFO ][http                     ] [Enforcer] bound_address {inet[/0:0:0:0:0:0:0:0:9201]}, publish_address {inet[/192.168.20.15:9201]}
[2015-12-22 17:17:22,366][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: started
[2015-12-22 17:17:22,984][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: stopping ...
[2015-12-22 17:17:23,032][INFO ][discovery.zen            ] [Enforcer] master_left [[Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]]], reason [shut_down]
[2015-12-22 17:17:23,034][INFO ][cluster.service          ] [Enforcer] master {new [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]], previous [Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]]}, removed {[Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]],}, reason: zen-disco-master_failed ([Prime Mover][iZVy0ay4QfW06RX0QWqmTw][inet[/192.168.20.15:9300]])
[2015-12-22 17:17:23,077][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: stopped
[2015-12-22 17:17:23,077][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: closing ...
[2015-12-22 17:17:23,089][INFO ][node                     ] [Prime Mover] {0.20.6}[42419]: closed
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x692e020f, /192.168.20.15:51843 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x1d51df36, /192.168.20.15:51838 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xf9497a94, /192.168.20.15:51840 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x61db8f3e, /192.168.20.15:51842 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x66937037, /192.168.20.15:51842 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xf1820e43, /192.168.20.15:51843 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x36bb7e4a, /192.168.20.15:51839 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xc2591557, /192.168.20.15:51841 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xf325eb8e, /192.168.20.15:51840 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xb5de5ded, /192.168.20.15:51839 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xb9a4997e, /192.168.20.15:51844 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xda9a0850, /192.168.20.15:51845 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x07654d80, /192.168.20.15:51844 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xe811232d, /192.168.20.15:51845 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0x73e1be44, /192.168.20.15:51841 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,174][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xca8a330c, /192.168.20.15:51838 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:08:12,191][WARN ][transport.netty          ] [Enforcer] exception caught on transport layer [[id: 0xc113881f, /192.168.20.15:51837 => /192.168.20.15:9301]], closing connection
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-22 22:12:03,406][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:16:04,002][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:20:04,603][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:24:05,208][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:28:05,807][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:32:06,408][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:36:07,005][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:40:07,602][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:44:08,206][WARN ][cluster.service          ] [Enforcer] failed to reconnect to node [Enforcer][u1kdcT1TTi2lwRKsI-haAg][inet[/192.168.20.15:9301]]
org.elasticsearch.transport.ConnectTransportException: [Enforcer][inet[/192.168.20.15:9301]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:136)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:82)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2015-12-22 22:47:09,942][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: stopping ...
[2015-12-22 22:47:28,711][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: stopped
[2015-12-22 22:47:28,711][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: closing ...
[2015-12-22 22:47:28,719][INFO ][node                     ] [Enforcer] {0.20.6}[58916]: closed
